/* Generated by the Nim Compiler v1.9.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI704643086 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI956301390 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI956301396 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555176;
var NNI956301396 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI956301390, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI956301396.node = NNI956301396;
var NNI704643086 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI704643086.node = NNI704643086;

function mnewString(len_33556836) {
        return new Array(len_33556836);
  

  
}

function toJSStr(s_33556747) {
  var result_33556748 = null;

    var res_33556782 = newSeq_33556765((s_33556747).length);
    var i_33556783 = 0;
    var j_33556784 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556783 < (s_33556747).length)) break Label2;
          var c_33556785 = s_33556747[i_33556783];
          if ((c_33556785 < 128)) {
          res_33556782[j_33556784] = String.fromCharCode(c_33556785);
          i_33556783 += 1;
          }
          else {
            var helper_33556798 = newSeq_33556765(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556799 = c_33556785.toString(16);
                  if ((((code_33556799) == null ? 0 : (code_33556799).length) == 1)) {
                  helper_33556798.push("%0");;
                  }
                  else {
                  helper_33556798.push("%");;
                  }
                  
                  helper_33556798.push(code_33556799);;
                  i_33556783 += 1;
                  if ((((s_33556747).length <= i_33556783) || (s_33556747[i_33556783] < 128))) {
                  break Label3;
                  }
                  
                  c_33556785 = s_33556747[i_33556783];
                }
            };
++excHandler;
            try {
            res_33556782[j_33556784] = decodeURIComponent(helper_33556798.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556782[j_33556784] = helper_33556798.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556784 += 1;
        }
    };
    if (res_33556782.length < j_33556784) { for (var i = res_33556782.length ; i < j_33556784 ; ++i) res_33556782.push(null); }
               else { res_33556782.length = j_33556784; };
    result_33556748 = res_33556782.join("");

  return result_33556748;

}

function raiseException(e_33556607, ename_33556608) {
    e_33556607.name = ename_33556608;
    if ((excHandler == 0)) {
    unhandledException(e_33556607);
    }
    
    throw e_33556607;

  
}

function addInt(a_33556883, b_33556884) {
        var result = a_33556883 + b_33556884;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557132, a_33557133, b_33557134) {
  var result_33557135 = 0;

  BeforeRet: {
    if (((a_33557133 <= i_33557132) && (i_33557132 <= b_33557134))) {
    result_33557135 = i_33557132;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557135;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557083, src_33557084, ti_33557085) {
  var result_33557094 = null;

    switch (ti_33557085.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557074(ti_33557085))) {
      result_33557094 = src_33557084;
      }
      else {
        result_33557094 = [src_33557084[0], src_33557084[1]];
      }
      
      break;
    case 19:
            if (dest_33557083 === null || dest_33557083 === undefined) {
        dest_33557083 = {};
      }
      else {
        for (var key in dest_33557083) { delete dest_33557083[key]; }
      }
      for (var key in src_33557084) { dest_33557083[key] = src_33557084[key]; }
      result_33557094 = dest_33557083;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557085.base == null))) {
      result_33557094 = nimCopy(dest_33557083, src_33557084, ti_33557085.base);
      }
      else {
      if ((ti_33557085.kind == 17)) {
      result_33557094 = (dest_33557083 === null || dest_33557083 === undefined) ? {m_type: ti_33557085} : dest_33557083;
      }
      else {
        result_33557094 = (dest_33557083 === null || dest_33557083 === undefined) ? {} : dest_33557083;
      }
      }
      nimCopyAux(result_33557094, src_33557084, ti_33557085.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557084)) { 
        if(dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
          dest_33557083 = new src_33557084.constructor(src_33557084);
        } else {
          dest_33557083.set(src_33557084, 0);
        }
        result_33557094 = dest_33557083;
      } else {
        if (src_33557084 === null) {
          result_33557094 = null;
        }
        else {
          if (dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
            dest_33557083 = new Array(src_33557084.length);
          }
          result_33557094 = dest_33557083;
          for (var i = 0; i < src_33557084.length; ++i) {
            result_33557094[i] = nimCopy(result_33557094[i], src_33557084[i], ti_33557085.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557084 === null) {
        result_33557094 = null;
      }
      else {
        if (dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
          dest_33557083 = new Array(src_33557084.length);
        }
        result_33557094 = dest_33557083;
        for (var i = 0; i < src_33557084.length; ++i) {
          result_33557094[i] = nimCopy(result_33557094[i], src_33557084[i], ti_33557085.base);
        }
      }
    
      break;
    case 28:
            if (src_33557084 !== null) {
        result_33557094 = src_33557084.slice(0);
      }
    
      break;
    default: 
      result_33557094 = src_33557084;
      break;
    }

  return result_33557094;

}

function chckIndx(i_33557127, a_33557128, b_33557129) {
  var result_33557130 = 0;

  BeforeRet: {
    if (((a_33557128 <= i_33557127) && (i_33557127 <= b_33557129))) {
    result_33557130 = i_33557127;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557127, a_33557128, b_33557129);
    }
    
  };

  return result_33557130;

}

function makeNimstrLit(c_33556741) {
      var result = [];
  for (var i = 0; i < c_33556741.length; ++i) {
    result[i] = c_33556741.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33556887, b_33556888) {
        var result = a_33556887 - b_33556888;
    checkOverflowInt(result);
    return result;
  

  
}

function cstrToNimstr(c_33556744) {
      var ln = c_33556744.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556744.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556744.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33556891, b_33556892) {
        var result = a_33556891 * b_33556892;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_33556941, b_33556942) {
    var Temporary1;

  var result_33556943 = 0;

  BeforeRet: {
    if ((b_33556942 <= a_33556941)) {
    Temporary1 = a_33556941;
    }
    else {
    Temporary1 = b_33556942;
    }
    
    result_33556943 = Temporary1;
    break BeforeRet;
  };

  return result_33556943;

}

function nimMin(a_33556937, b_33556938) {
    var Temporary1;

  var result_33556939 = 0;

  BeforeRet: {
    if ((a_33556937 <= b_33556938)) {
    Temporary1 = a_33556937;
    }
    else {
    Temporary1 = b_33556938;
    }
    
    result_33556939 = Temporary1;
    break BeforeRet;
  };

  return result_33556939;

}

function addChar(x_33557198, c_33557199) {
    x_33557198.push(c_33557199);

  
}
var objectID_1191182500 = [0];

function setTheme(theme_553648134) {
    document.documentElement.setAttribute("data-theme", theme_553648134);
    window.localStorage.setItem("theme", theme_553648134);

  
}

function add_33556386(x_33556387, x_33556387_Idx, y_33556388) {
          if (x_33556387[x_33556387_Idx] === null) { x_33556387[x_33556387_Idx] = []; }
      var off = x_33556387[x_33556387_Idx].length;
      x_33556387[x_33556387_Idx].length += y_33556388.length;
      for (var i = 0; i < y_33556388.length; ++i) {
        x_33556387[x_33556387_Idx][off+i] = y_33556388.charCodeAt(i);
      }
    

  
}

function newSeq_33556765(len_33556767) {
  var result_33556768 = [];

    result_33556768 = new Array(len_33556767); for (var i = 0 ; i < len_33556767 ; ++i) { result_33556768[i] = null; }
  return result_33556768;

}

function unhandledException(e_33556603) {
    var buf_33556604 = [[]];
    if (!(((e_33556603.message).length == 0))) {
    buf_33556604[0].push.apply(buf_33556604[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556604[0].push.apply(buf_33556604[0], e_33556603.message);;
    }
    else {
    buf_33556604[0].push.apply(buf_33556604[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556604[0].push.apply(buf_33556604[0], [32,91]);;
    add_33556386(buf_33556604, 0, e_33556603.name);
    buf_33556604[0].push.apply(buf_33556604[0], [93,10]);;
    var cbuf_33556605 = toJSStr(buf_33556604[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556605);
  }
  else {
    throw cbuf_33556605;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556881) {
        if (a_33556881 > 2147483647 || a_33556881 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990048(result_301990050, result_301990050_Idx, x_301990051, start_301990052, n_301990053) {
    var Temporary1;

    var old_301990054 = (result_301990050[result_301990050_Idx]).length;
    if (result_301990050[result_301990050_Idx].length < (Temporary1 = chckRange(addInt(old_301990054, n_301990053), 0, 2147483647), Temporary1)) { for (var i = result_301990050[result_301990050_Idx].length; i < Temporary1; ++i) result_301990050[result_301990050_Idx].push(0); }
         else {result_301990050[result_301990050_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990068 = 0;
      var i_553649084 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553649084 < n_301990053)) break Label4;
            iHEX60gensym4_301990068 = i_553649084;
            result_301990050[result_301990050_Idx][chckIndx(addInt(old_301990054, iHEX60gensym4_301990068), 0, (result_301990050[result_301990050_Idx]).length - 1)] = x_301990051.charCodeAt(chckIndx(addInt(start_301990052, iHEX60gensym4_301990068), 0, (x_301990051).length - 1));
            i_553649084 = addInt(i_553649084, 1);
          }
      };
    };

  
}

function addChars_301990044(result_301990046, result_301990046_Idx, x_301990047) {
    addChars_301990048(result_301990046, result_301990046_Idx, x_301990047, 0, ((x_301990047) == null ? 0 : (x_301990047).length));

  
}

function addInt_301990069(result_301990070, result_301990070_Idx, x_301990071) {
    addChars_301990044(result_301990070, result_301990070_Idx, ((x_301990071) + ""));

  
}

function addInt_301990087(result_301990088, result_301990088_Idx, x_301990089) {
    addInt_301990069(result_301990088, result_301990088_Idx, x_301990089);

  
}

function HEX24_385875976(x_385875977) {
  var result_385875978 = [[]];

    addInt_301990087(result_385875978, 0, x_385875977);

  return result_385875978[0];

}

function isFatPointer_33557074(ti_33557075) {
  var result_33557076 = false;

  BeforeRet: {
    result_33557076 = !((ConstSet1[ti_33557075.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557076;

}

function nimCopyAux(dest_33557087, src_33557088, n_33557089) {
    switch (n_33557089.kind) {
    case 0:
      break;
    case 1:
            dest_33557087[n_33557089.offset] = nimCopy(dest_33557087[n_33557089.offset], src_33557088[n_33557089.offset], n_33557089.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557089.sons.length; i++) {
      nimCopyAux(dest_33557087, src_33557088, n_33557089.sons[i]);
    }
    
      break;
    case 3:
            dest_33557087[n_33557089.offset] = nimCopy(dest_33557087[n_33557089.offset], src_33557088[n_33557089.offset], n_33557089.typ);
      for (var i = 0; i < n_33557089.sons.length; ++i) {
        nimCopyAux(dest_33557087, src_33557088, n_33557089.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556694, a_33556695, b_33556696) {
    var Temporary1;

    if ((b_33556696 < a_33556695)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_385875976(i_33556694) || [],[32,110,111,116,32,105,110,32] || [],HEX24_385875976(a_33556695) || [],[32,46,46,32] || [],HEX24_385875976(b_33556696) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_268435493(message_268435496) {
    raiseException({message: nimCopy(null, message_268435496, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_268435491(msg_268435492) {
    sysFatal_268435493(msg_268435492);

  
}

function failedAssertImpl_268435515(msg_268435516) {
    raiseAssert_268435491(msg_268435516);

  
}

function onDOMLoaded(e_553648155) {
            
function HEX3Aanonymous_553648179(event_553648180) {
                event_553648180.target.parentNode.style.display = "none";
                event_553648180.target.parentNode.nextSibling.style.display = "inline";

              
            }

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_553648178 = null;
      var colontmp__553649075 = [];
      colontmp__553649075 = document.getElementsByClassName("pragmadots");
      var i_553649077 = 0;
      var L_553649078 = (colontmp__553649075).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649077 < L_553649078)) break Label3;
            pragmaDots_553648178 = colontmp__553649075[chckIndx(i_553649077, 0, (colontmp__553649075).length - 1)];
            pragmaDots_553648178.onclick = HEX3Aanonymous_553648179;
            i_553649077 = addInt(i_553649077, 1);
            if (!(((colontmp__553649075).length == L_553649078))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function isWhitespace_553648449(x_553648450) {
  var result_553648451 = false;

    result_553648451 = (((x_553648450.nodeName == "#text") && !/\S/.test(x_553648450.textContent)) || (x_553648450.nodeName == "#comment"));

  return result_553648451;

}

function toToc_553648452(x_553648453, father_553648454) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_553648453.nodeName == "UL")) {
    var f_553648462 = {heading: null, kids: [], sortId: (father_553648454.kids).length, doSort: false};
    var i_553648463 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_553648463 < x_553648453.childNodes.length)) break Label2;
          var nxt_553648464 = addInt(i_553648463, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_553648464 < x_553648453.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_553648449(x_553648453.childNodes[nxt_553648464]);                }              if (!Temporary5) break Label4;
                nxt_553648464 = addInt(nxt_553648464, 1);
              }
          };
            if (!(nxt_553648464 < x_553648453.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_553648453.childNodes[i_553648463].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_553648453.childNodes[i_553648463].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_553648453.childNodes[nxt_553648464].nodeName == "UL");            }          if (Temporary6) {
          var e_553648477 = {heading: x_553648453.childNodes[i_553648463].childNodes[0], kids: [], sortId: (f_553648462.kids).length, doSort: false};
          var it_553648478 = x_553648453.childNodes[nxt_553648464];
          Label9: {
            var j_553648483 = 0;
            var colontmp__553649091 = 0;
            colontmp__553649091 = it_553648478.childNodes.length;
            var i_553649092 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_553649092 < colontmp__553649091)) break Label11;
                  j_553648483 = i_553649092;
                  toToc_553648452(it_553648478.childNodes[j_553648483], e_553648477);
                  i_553649092 = addInt(i_553649092, 1);
                }
            };
          };
          f_553648462.kids.push(e_553648477);;
          i_553648463 = addInt(nxt_553648464, 1);
          }
          else {
            toToc_553648452(x_553648453.childNodes[i_553648463], f_553648462);
            i_553648463 = addInt(i_553648463, 1);
          }
          
        }
    };
    father_553648454.kids.push(f_553648462);;
    }
    else {
    if (isWhitespace_553648449(x_553648453)) {
    }
    else {
    if ((x_553648453.nodeName == "LI")) {
    var idx_553648501 = [];
    Label12: {
      var i_553648506 = 0;
      var colontmp__553649095 = 0;
      colontmp__553649095 = x_553648453.childNodes.length;
      var i_553649096 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_553649096 < colontmp__553649095)) break Label14;
            i_553648506 = i_553649096;
            if (!(isWhitespace_553648449(x_553648453.childNodes[i_553648506]))) {
            idx_553648501.push(i_553648506);;
            }
            
            i_553649096 = addInt(i_553649096, 1);
          }
      };
    };
      if (!((idx_553648501).length == 2)) Temporary15 = false; else {        Temporary15 = (x_553648453.childNodes[idx_553648501[chckIndx(1, 0, (idx_553648501).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_553648522 = {heading: x_553648453.childNodes[idx_553648501[chckIndx(0, 0, (idx_553648501).length - 1)]], kids: [], sortId: (father_553648454.kids).length, doSort: false};
    var it_553648523 = x_553648453.childNodes[idx_553648501[chckIndx(1, 0, (idx_553648501).length - 1)]];
    Label16: {
      var j_553648528 = 0;
      var colontmp__553649099 = 0;
      colontmp__553649099 = it_553648523.childNodes.length;
      var i_553649100 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_553649100 < colontmp__553649099)) break Label18;
            j_553648528 = i_553649100;
            toToc_553648452(it_553648523.childNodes[j_553648528], e_553648522);
            i_553649100 = addInt(i_553649100, 1);
          }
      };
    };
    father_553648454.kids.push(e_553648522);;
    }
    else {
      Label19: {
        var i_553648537 = 0;
        var colontmp__553649103 = 0;
        colontmp__553649103 = x_553648453.childNodes.length;
        var i_553649104 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_553649104 < colontmp__553649103)) break Label21;
              i_553648537 = i_553649104;
              toToc_553648452(x_553648453.childNodes[i_553648537], father_553648454);
              i_553649104 = addInt(i_553649104, 1);
            }
        };
      };
    }
    
    }
    else {
    father_553648454.kids.push({heading: x_553648453, kids: [], sortId: (father_553648454.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems_553648286(x_553648287, heading_553648288, items_553648289, items_553648289_Idx) {
  BeforeRet: {
    if ((x_553648287 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_553648287.heading == null)) && (x_553648287.heading.textContent == heading_553648288))) {
    Label1: {
      var i_553648306 = 0;
      var colontmp__553649107 = 0;
      colontmp__553649107 = (x_553648287.kids).length;
      var i_553649108 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649108 < colontmp__553649107)) break Label3;
            i_553648306 = i_553649108;
            items_553648289[items_553648289_Idx].push(x_553648287.kids[chckIndx(i_553648306, 0, (x_553648287.kids).length - 1)].heading);;
            i_553649108 = addInt(i_553649108, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_553648332 = null;
        var i_553649112 = 0;
        var L_553649113 = (x_553648287.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_553649112 < L_553649113)) break Label6;
              k_553648332 = x_553648287.kids[chckIndx(i_553649112, 0, (x_553648287.kids).length - 1)];
              extractItems_553648286(k_553648332, heading_553648288, items_553648289, items_553648289_Idx);
              i_553649112 = addInt(i_553649112, 1);
              if (!(((x_553648287.kids).length == L_553649113))) {
              failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree_553648217(tag_553648218, kids_553648219) {
  var result_553648220 = null;

    result_553648220 = document.createElement(tag_553648218);
    Label1: {
      var k_553648234 = null;
      var i_553649125 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649125 < (kids_553648219).length)) break Label3;
            k_553648234 = kids_553648219[chckIndx(i_553649125, 0, (kids_553648219).length - 1)];
            result_553648220.appendChild(k_553648234);
            i_553649125 = addInt(i_553649125, 1);
          }
      };
    };

  return result_553648220;

}

function text_553648242(s_553648243) {
  var result_553648244 = null;

    result_553648244 = document.createTextNode(s_553648243);

  return result_553648244;

}

function uncovered_553648603(x_553648604) {
    var Temporary1;

  var result_553648605 = null;

  BeforeRet: {
    if ((((x_553648604.kids).length == 0) && !((x_553648604.heading == null)))) {
    if (!(x_553648604.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_553648604;
    }
    else {
    Temporary1 = null;
    }
    
    result_553648605 = Temporary1;
    break BeforeRet;
    }
    
    result_553648605 = {heading: x_553648604.heading, kids: [], sortId: x_553648604.sortId, doSort: x_553648604.doSort};
    Label2: {
      var k_553648620 = null;
      var i_553649132 = 0;
      var L_553649133 = (x_553648604.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_553649132 < L_553649133)) break Label4;
            k_553648620 = x_553648604.kids[chckIndx(i_553649132, 0, (x_553648604.kids).length - 1)];
            var y_553648621 = uncovered_553648603(k_553648620);
            if (!((y_553648621 == null))) {
            result_553648605.kids.push(y_553648621);;
            }
            
            i_553649132 = addInt(i_553649132, 1);
            if (!(((x_553648604.kids).length == L_553649133))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_553648605.kids).length == 0)) {
    result_553648605 = null;
    }
    
  };

  return result_553648605;

}

function mergeTocs_553648633(orig_553648634, news_553648635) {
  var result_553648636 = null;

    result_553648636 = uncovered_553648603(orig_553648634);
    if ((result_553648636 == null)) {
    result_553648636 = news_553648635;
    }
    else {
      Label1: {
        var i_553648648 = 0;
        var colontmp__553649128 = 0;
        colontmp__553649128 = (news_553648635.kids).length;
        var i_553649129 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_553649129 < colontmp__553649128)) break Label3;
              i_553648648 = i_553649129;
              result_553648636.kids.push(news_553648635.kids[chckIndx(i_553648648, 0, (news_553648635.kids).length - 1)]);;
              i_553649129 = addInt(i_553649129, 1);
            }
        };
      };
    }
    

  return result_553648636;

}

function buildToc_553648653(orig_553648654, types_553648655, procs_553648656) {
  var result_553648657 = null;

    var newStuff_553648662 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_553648666 = null;
      var i_553649120 = 0;
      var L_553649121 = (types_553648655).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649120 < L_553649121)) break Label3;
            t_553648666 = types_553648655[chckIndx(i_553649120, 0, (types_553648655).length - 1)];
            var c_553648671 = {heading: t_553648666.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_553648666.__karaxMarker__ = true;
            Label4: {
              var p_553648675 = null;
              var i_553649117 = 0;
              var L_553649118 = (procs_553648656).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_553649117 < L_553649118)) break Label6;
                    p_553648675 = procs_553648656[chckIndx(i_553649117, 0, (procs_553648656).length - 1)];
                    if (!(p_553648675.hasOwnProperty('__karaxMarker__'))) {
                    var xx_553648676 = p_553648675.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_553648676).length == 1) && (xx_553648676[chckIndx(0, 0, (xx_553648676).length - 1)].textContent == t_553648666.textContent))) {
                    var q_553648681 = tree_553648217("A", [text_553648242(p_553648675.title)]);
                    q_553648681.setAttribute("href", p_553648675.getAttribute("href"));
                    c_553648671.kids.push({heading: q_553648681, kids: [], sortId: 0, doSort: false});;
                    p_553648675.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_553649117 = addInt(i_553649117, 1);
                    if (!(((procs_553648656).length == L_553649118))) {
                    failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_553648662.kids.push(c_553648671);;
            i_553649120 = addInt(i_553649120, 1);
            if (!(((types_553648655).length == L_553649121))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553648657 = mergeTocs_553648633(orig_553648654, newStuff_553648662);

  return result_553648657;

}

function add_553648235(parent_553648236, kid_553648237) {
    if (((parent_553648236.nodeName == "TR") && ((kid_553648237.nodeName == "TD") || (kid_553648237.nodeName == "TH")))) {
    var k_553648238 = document.createElement("TD");
    k_553648238.appendChild(kid_553648237);
    parent_553648236.appendChild(k_553648238);
    }
    else {
    parent_553648236.appendChild(kid_553648237);
    }
    

  
}

function setClass_553648239(e_553648240, value_553648241) {
    e_553648240.setAttribute("class", value_553648241);

  
}

function toHtml_553648351(x_553648352, isRoot_553648353) {
    
function HEX3Aanonymous_553648371(a_553648372, b_553648373) {
      var result_553648374 = 0;

      BeforeRet: {
        if ((!((a_553648372.heading == null)) && !((b_553648373.heading == null)))) {
        var x_553648383 = a_553648372.heading.textContent;
        var y_553648384 = b_553648373.heading.textContent;
        if ((x_553648383 < y_553648384)) {
        result_553648374 = -1;
        break BeforeRet;
        }
        
        if ((y_553648384 < x_553648383)) {
        result_553648374 = 1;
        break BeforeRet;
        }
        
        result_553648374 = 0;
        break BeforeRet;
        }
        else {
          result_553648374 = subInt(a_553648372.sortId, b_553648373.sortId);
          break BeforeRet;
        }
        
      };

      return result_553648374;

    }

  var result_553648354 = null;

  BeforeRet: {
    if ((x_553648352 == null)) {
    result_553648354 = null;
    break BeforeRet;
    }
    
    if (((x_553648352.kids).length == 0)) {
    if ((x_553648352.heading == null)) {
    result_553648354 = null;
    break BeforeRet;
    }
    
    result_553648354 = x_553648352.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_553648354 = tree_553648217("DIV", []);
    if ((!((x_553648352.heading == null)) && !(x_553648352.heading.hasOwnProperty('__karaxMarker__')))) {
    add_553648235(result_553648354, x_553648352.heading.cloneNode(true));
    }
    
    var ul_553648370 = tree_553648217("UL", []);
    if (isRoot_553648353) {
    setClass_553648239(ul_553648370, "simple simple-toc");
    }
    else {
    setClass_553648239(ul_553648370, "simple");
    }
    
    if (x_553648352.doSort) {
    x_553648352.kids.sort(HEX3Aanonymous_553648371);
    }
    
    Label1: {
      var k_553648396 = null;
      var i_553649136 = 0;
      var L_553649137 = (x_553648352.kids).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649136 < L_553649137)) break Label3;
            k_553648396 = x_553648352.kids[chckIndx(i_553649136, 0, (x_553648352.kids).length - 1)];
            var y_553648397 = toHtml_553648351(k_553648396, false);
            if (!((y_553648397 == null))) {
            add_553648235(ul_553648370, tree_553648217("LI", [y_553648397]));
            }
            
            i_553649136 = addInt(i_553649136, 1);
            if (!(((x_553648352.kids).length == L_553649137))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_553648370.childNodes.length == 0))) {
    add_553648235(result_553648354, ul_553648370);
    }
    
    if ((result_553648354.childNodes.length == 0)) {
    result_553648354 = null;
    }
    
  };

  return result_553648354;

}

function replaceById_553648245(id_553648246, newTree_553648247) {
    var x_553648248 = document.getElementById(id_553648246);
    x_553648248.parentNode.replaceChild(newTree_553648247, x_553648248);
    newTree_553648247.id = id_553648246;

  
}

function togglevis_553648704(d_553648705) {
    if ((d_553648705.style.display == "none")) {
    d_553648705.style.display = "inline";
    }
    else {
      d_553648705.style.display = "none";
    }
    

  
}

function groupBy(value_553648707) {
    var toc_553648708 = document.getElementById("toc-list");
    if ((alternative_553648703[0] == null)) {
    var tt_553648716 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc_553648452(toc_553648708, tt_553648716);
    tt_553648716 = tt_553648716.kids[chckIndx(0, 0, (tt_553648716.kids).length - 1)];
    var types_553648721 = [[]];
    var procs_553648726 = [[]];
    extractItems_553648286(tt_553648716, "Types", types_553648721, 0);
    extractItems_553648286(tt_553648716, "Procs", procs_553648726, 0);
    extractItems_553648286(tt_553648716, "Converters", procs_553648726, 0);
    extractItems_553648286(tt_553648716, "Methods", procs_553648726, 0);
    extractItems_553648286(tt_553648716, "Templates", procs_553648726, 0);
    extractItems_553648286(tt_553648716, "Macros", procs_553648726, 0);
    extractItems_553648286(tt_553648716, "Iterators", procs_553648726, 0);
    var ntoc_553648727 = buildToc_553648653(tt_553648716, types_553648721[0], procs_553648726[0]);
    var x_553648728 = toHtml_553648351(ntoc_553648727, true);
    alternative_553648703[0] = tree_553648217("DIV", [x_553648728]);
    }
    
    if ((value_553648707 == "type")) {
    replaceById_553648245("tocRoot", alternative_553648703[0]);
    }
    else {
    replaceById_553648245("tocRoot", tree_553648217("DIV", []));
    }
    
    togglevis_553648704(document.getElementById("toc-list"));

  
}

function HEX5BHEX5D_721421591(s_721421594, x_721421595) {
  var result_721421596 = [];

    var a_721421598 = x_721421595.a;
    var L_721421600 = addInt(subInt(subInt((s_721421594).length, x_721421595.b), a_721421598), 1);
    result_721421596 = nimCopy(null, mnewString(chckRange(L_721421600, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_721421605 = 0;
      var i_553649146 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649146 < L_721421600)) break Label3;
            i_721421605 = i_553649146;
            result_721421596[chckIndx(i_721421605, 0, (result_721421596).length - 1)] = s_721421594[chckIndx(addInt(i_721421605, a_721421598), 0, (s_721421594).length - 1)];
            i_553649146 = addInt(i_553649146, 1);
          }
      };
    };

  return result_721421596;

}

function HEX2EHEX2E_956301408(a_956301411, b_956301412) {
  var result_956301415 = ({a: 0, b: 0});

    result_956301415 = nimCopy(result_956301415, {a: a_956301411, b: b_956301412}, NTI956301396);

  return result_956301415;

}
async function loadIndex_553648873() {
  var result_553648875 = null;

  BeforeRet: {
    var indexURL_553648881 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_553648907 = HEX5BHEX5D_721421591(cstrToNimstr(indexURL_553648881), HEX2EHEX2E_956301408(0, 14));
    var resp_553648919 = (await (await fetch(indexURL_553648881)).text());
    var indexElem_553648920 = document.createElement("div");
    indexElem_553648920.innerHTML = resp_553648919;
    Label1: {
      var href_553648942 = null;
      var colontmp__553649140 = [];
      colontmp__553649140 = indexElem_553648920.getElementsByClassName("reference");
      var i_553649142 = 0;
      var L_553649143 = (colontmp__553649140).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649142 < L_553649143)) break Label3;
            href_553648942 = colontmp__553649140[chckIndx(i_553649142, 0, (colontmp__553649140).length - 1)];
            href_553648942.setAttribute("href", toJSStr((rootURL_553648907 || []).concat(cstrToNimstr(href_553648942.getAttribute("href")) || [])));
            db_553648738[0].push(href_553648942);;
            contents_553648739[0].push(href_553648942.getAttribute("data-doc-search-tag"));;
            i_553649142 = addInt(i_553649142, 1);
            if (!(((colontmp__553649140).length == L_553649143))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553648875 = undefined;
    break BeforeRet;
  };

  return result_553648875;

}

function then_553649016(future_553649019, onSuccess_553649020, onReject_553649021) {
  var result_553649022 = null;

  BeforeRet: {
    var ret_553649032 = null;
    ret_553649032 = future_553649019.then(onSuccess_553649020, onReject_553649021)
    result_553649022 = ret_553649032;
    break BeforeRet;
  };

  return result_553649022;

}

function nsuToLowerAsciiChar(c_721420372) {
  var result_721420373 = 0;

    if ((ConstSet2[c_721420372] != undefined)) {
    result_721420373 = (c_721420372 ^ 32);
    }
    else {
      result_721420373 = c_721420372;
    }
    

  return result_721420373;

}

function fuzzyMatch_704643088(pattern_704643089, str_704643090) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_704643093 = {Field0: 0, Field1: false};

    var scoreState_704643094 = -100;
    var headerMatched_704643095 = false;
    var unmatchedLeadingCharCount_704643096 = 0;
    var consecutiveMatchCount_704643097 = 0;
    var strIndex_704643098 = 0;
    var patIndex_704643099 = 0;
    var score_704643100 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_704643098 < ((str_704643090) == null ? 0 : (str_704643090).length)) && (patIndex_704643099 < ((pattern_704643089) == null ? 0 : (pattern_704643089).length)))) break Label2;
          Label3: {
            var patternChar_704643103 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(patIndex_704643099, 0, (pattern_704643089).length - 1)));
            var strChar_704643104 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1)));
            if ((ConstSet3[patternChar_704643103] != undefined)) {
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_704643104] != undefined)) {
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((!(headerMatched_704643095) && (strChar_704643104 == 58))) {
            headerMatched_704643095 = true;
            scoreState_704643094 = -100;
            score_704643100 = ((Math.floor((0.5 * score_704643100))) | 0);
            patIndex_704643099 = 0;
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((strChar_704643104 == patternChar_704643103)) {
            switch (scoreState_704643094) {
            case -100:
            case 20:
              scoreState_704643094 = 10;
              break;
            case 0:
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_704643097 = addInt(consecutiveMatchCount_704643097, 1);
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, mulInt(5, consecutiveMatchCount_704643097));
              if ((scoreState_704643094 == 10)) {
              score_704643100 = addInt(score_704643100, 10);
              }
              
              var onBoundary_704643156 = (patIndex_704643099 == ((pattern_704643089) == null ? -1 : (pattern_704643089).length - 1));
              if ((!(onBoundary_704643156) && (strIndex_704643098 < ((str_704643090) == null ? -1 : (str_704643090).length - 1)))) {
              var nextPatternChar_704643157 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(addInt(patIndex_704643099, 1), 0, (pattern_704643089).length - 1)));
              var nextStrChar_704643158 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(addInt(strIndex_704643098, 1), 0, (str_704643090).length - 1)));
              if (!!((ConstSet5[nextStrChar_704643158] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_704643158 == nextPatternChar_704643157));              }              onBoundary_704643156 = Temporary4;
              }
              
              if (onBoundary_704643156) {
              scoreState_704643094 = 20;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            case -1:
            case -3:
              if (!((ConstSet6[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_704643182 = Temporary5;
              if (isLeadingChar_704643182) {
              scoreState_704643094 = 10;
              }
              else {
                scoreState_704643094 = 0;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            }
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            }
            else {
              switch (scoreState_704643094) {
              case -100:
                scoreState_704643094 = -3;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              case 5:
                scoreState_704643094 = -1;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                consecutiveMatchCount_704643097 = 0;
                break;
              case -3:
                if ((unmatchedLeadingCharCount_704643096 < 3)) {
                scoreState_704643094 = -3;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                }
                
                unmatchedLeadingCharCount_704643096 = addInt(unmatchedLeadingCharCount_704643096, 1);
                break;
              default: 
                scoreState_704643094 = -1;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              }
            }
            
            strIndex_704643098 = addInt(strIndex_704643098, 1);
          };
        }
    };
      if (!(patIndex_704643099 == ((pattern_704643089) == null ? 0 : (pattern_704643089).length))) Temporary7 = false; else {        if ((strIndex_704643098 == ((str_704643090) == null ? 0 : (str_704643090).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_704643100 = addInt(score_704643100, 10);
    }
    
    var colontmp__553649160 = nimMax(0, score_704643100);
    var colontmp__553649161 = (0 < score_704643100);
    result_704643093 = nimCopy(result_704643093, {Field0: colontmp__553649160, Field1: colontmp__553649161}, NTI704643086);

  return result_704643093;

}

function escapeCString_553648740(x_553648741, x_553648741_Idx) {
    var s_553648742 = [];
    Label1: {
      var c_553648743 = 0;
      var iHEX60gensym6_553649164 = 0;
      var nHEX60gensym6_553649165 = ((x_553648741[x_553648741_Idx]) == null ? 0 : (x_553648741[x_553648741_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym6_553649164 < nHEX60gensym6_553649165)) break Label3;
            c_553648743 = x_553648741[x_553648741_Idx].charCodeAt(chckIndx(iHEX60gensym6_553649164, 0, (x_553648741[x_553648741_Idx]).length - 1));
            switch (c_553648743) {
            case 60:
              s_553648742.push.apply(s_553648742, [38,108,116,59]);;
              break;
            case 62:
              s_553648742.push.apply(s_553648742, [38,103,116,59]);;
              break;
            default: 
              addChar(s_553648742, c_553648743);;
              break;
            }
            iHEX60gensym6_553649164 = addInt(iHEX60gensym6_553649164, 1);
          }
      };
    };
    x_553648741[x_553648741_Idx] = toJSStr(s_553648742);

  
}

function dosearch_553648744(value_553648745) {
    
function HEX3Aanonymous_553648771(a_553648776, b_553648777) {
      var result_553648782 = 0;

        result_553648782 = subInt(b_553648777["Field1"], a_553648776["Field1"]);

      return result_553648782;

    }

  var result_553648746 = null;

  BeforeRet: {
    if (((db_553648738[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_553648750 = tree_553648217("UL", []);
    result_553648746 = tree_553648217("DIV", []);
    setClass_553648239(result_553648746, "search_results");
    var matches_553648755 = [];
    Label1: {
      var i_553648763 = 0;
      var colontmp__553649150 = 0;
      colontmp__553649150 = (db_553648738[0]).length;
      var i_553649151 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649151 < colontmp__553649150)) break Label3;
            i_553648763 = i_553649151;
            Label4: {
              var c_553648764 = contents_553648739[0][chckIndx(i_553648763, 0, (contents_553648739[0]).length - 1)];
              if (((c_553648764 == "Examples") || (c_553648764 == "PEG construction"))) {
              break Label4;
              }
              
              var colontmp__553649157 = fuzzyMatch_704643088(value_553648745, c_553648764);
              var score_553648765 = colontmp__553649157["Field0"];
              var matched_553648766 = colontmp__553649157["Field1"];
              if (matched_553648766) {
              matches_553648755.push({Field0: db_553648738[0][chckIndx(i_553648763, 0, (db_553648738[0]).length - 1)], Field1: score_553648765});;
              }
              
            };
            i_553649151 = addInt(i_553649151, 1);
          }
      };
    };
    matches_553648755.sort(HEX3Aanonymous_553648771);
    Label5: {
      var i_553648799 = 0;
      var colontmp__553649154 = 0;
      colontmp__553649154 = nimMin((matches_553648755).length, 29);
      var i_553649155 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_553649155 < colontmp__553649154)) break Label7;
            i_553648799 = i_553649155;
            matches_553648755[chckIndx(i_553648799, 0, (matches_553648755).length - 1)]["Field0"].innerHTML = matches_553648755[chckIndx(i_553648799, 0, (matches_553648755).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString_553648740(matches_553648755[chckIndx(i_553648799, 0, (matches_553648755).length - 1)]["Field0"], "innerHTML");
            add_553648235(ul_553648750, tree_553648217("LI", [matches_553648755[chckIndx(i_553648799, 0, (matches_553648755).length - 1)]["Field0"]]));
            i_553649155 = addInt(i_553649155, 1);
          }
      };
    };
    if ((ul_553648750.childNodes.length == 0)) {
    add_553648235(result_553648746, tree_553648217("B", [text_553648242("no search results")]));
    }
    else {
      add_553648235(result_553648746, tree_553648217("B", [text_553648242("search results")]));
      add_553648235(result_553648746, ul_553648750);
    }
    
  };

  return result_553648746;

}

function search() {
    
function wrapper_553649001() {
        var elem_553649002 = document.getElementById("searchInput");
        var value_553649003 = elem_553649002.value;
        if (!((((value_553649003) == null ? 0 : (value_553649003).length) == 0))) {
        if ((oldtoc_553648996[0] == null)) {
        oldtoc_553648996[0] = document.getElementById("tocRoot");
        }
        
        var results_553649007 = dosearch_553648744(value_553649003);
        replaceById_553648245("tocRoot", results_553649007);
        }
        else {
        if (!((oldtoc_553648996[0] == null))) {
        replaceById_553648245("tocRoot", oldtoc_553648996[0]);
        }
        }

      
    }

    if ((loadIndexFut_553648999[0] == null)) {
    loadIndexFut_553648999[0] = loadIndex_553648873();
    var _ = then_553649016(loadIndexFut_553648999[0], wrapper_553649001, null);
    }
    
    if (!((timer_553648997[0] == null))) {
    clearTimeout(timer_553648997[0]);
    }
    
    timer_553648997[0] = setTimeout(wrapper_553649001, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var t_553648153 = window.localStorage.getItem("theme");
if ((t_553648153 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_553648153;
}

setTheme(Temporary1);
var alternative_553648703 = [null];
var db_553648738 = [[]];
var contents_553648739 = [[]];
var oldtoc_553648996 = [null];
var timer_553648997 = [null];
var loadIndexFut_553648999 = [null];
copyToClipboard();
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
